// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7bxf64kWkLQp1lPHDsP2PS41aljUO_7Q',
    appId: '1:259891443830:web:475d72f3506f14fbc7c757',
    messagingSenderId: '259891443830',
    projectId: 'fcm-quotes-app',
    authDomain: 'fcm-quotes-app.firebaseapp.com',
    storageBucket: 'fcm-quotes-app.firebasestorage.app',
    measurementId: 'G-CV2EEZSW0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApkHifiOHNk8clTb_FJFmnH1OQteMJCBw',
    appId: '1:259891443830:android:d08b56516ac06c1cc7c757',
    messagingSenderId: '259891443830',
    projectId: 'fcm-quotes-app',
    storageBucket: 'fcm-quotes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUFVDpJBMaXTwgcfwbguHHc6LqcMlWUtU',
    appId: '1:259891443830:ios:09af623214e04f50c7c757',
    messagingSenderId: '259891443830',
    projectId: 'fcm-quotes-app',
    storageBucket: 'fcm-quotes-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMessagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUFVDpJBMaXTwgcfwbguHHc6LqcMlWUtU',
    appId: '1:259891443830:ios:09af623214e04f50c7c757',
    messagingSenderId: '259891443830',
    projectId: 'fcm-quotes-app',
    storageBucket: 'fcm-quotes-app.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMessagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7bxf64kWkLQp1lPHDsP2PS41aljUO_7Q',
    appId: '1:259891443830:web:dabb4e1e017623d8c7c757',
    messagingSenderId: '259891443830',
    projectId: 'fcm-quotes-app',
    authDomain: 'fcm-quotes-app.firebaseapp.com',
    storageBucket: 'fcm-quotes-app.firebasestorage.app',
    measurementId: 'G-KSFQH8V8WN',
  );
}
