// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVb8xZ4gjevp8cx-KWAd4DVbYhmgl1ZIQ',
    appId: '1:101268382978:web:f7913ed6f781ce8987ce1b',
    messagingSenderId: '101268382978',
    projectId: 'fcm-flutter-quotes',
    authDomain: 'fcm-flutter-quotes.firebaseapp.com',
    storageBucket: 'fcm-flutter-quotes.firebasestorage.app',
    measurementId: 'G-7ZDF9NMJSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0L5g50IyWgwkSY524g7tO_b-fY1jmi8Q',
    appId: '1:101268382978:android:4d87ae53e207732087ce1b',
    messagingSenderId: '101268382978',
    projectId: 'fcm-flutter-quotes',
    storageBucket: 'fcm-flutter-quotes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0l1E_Bg2HHUx9K1fFCGMq9dvkIvTZo08',
    appId: '1:101268382978:ios:671f6c6960a58a2487ce1b',
    messagingSenderId: '101268382978',
    projectId: 'fcm-flutter-quotes',
    storageBucket: 'fcm-flutter-quotes.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0l1E_Bg2HHUx9K1fFCGMq9dvkIvTZo08',
    appId: '1:101268382978:ios:671f6c6960a58a2487ce1b',
    messagingSenderId: '101268382978',
    projectId: 'fcm-flutter-quotes',
    storageBucket: 'fcm-flutter-quotes.firebasestorage.app',
    iosBundleId: 'com.example.inclass17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVb8xZ4gjevp8cx-KWAd4DVbYhmgl1ZIQ',
    appId: '1:101268382978:web:78e7777052829bd687ce1b',
    messagingSenderId: '101268382978',
    projectId: 'fcm-flutter-quotes',
    authDomain: 'fcm-flutter-quotes.firebaseapp.com',
    storageBucket: 'fcm-flutter-quotes.firebasestorage.app',
    measurementId: 'G-13YC0TPBPQ',
  );
}
